INSERT INTO player (id, name, force, agility, instinct, stamina, level, health)
VALUES (1, 'Inna', 4, 3, 3, 3, 0, 1)

INSERT INTO player (id, name, force, agility, instinct, stamina, level, health)
VALUES (1, 'Sasha', 4, 3, 3, 3, 0, 1)

INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
VALUES (0, 3, 0)
INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
VALUES (20, 1, 0)
INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
VALUES (40, 1, 0)
INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
VALUES (65, 1, 0)
INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
VALUES (90, 3, 1)
INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
VALUES (120, 1, 0)
INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
VALUES (160, 1, 0)
INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
VALUES (210, 1, 0)
INSERT INTO EXPERIENCE_TABLE(experince, ability, level)
