CREATE TABLE ACCOUNT
(
  ID SERIAL NOT NULL,
  USERNAME VARCHAR (50),
  PASSWORD VARCHAR (255),
  CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID)
);

CREATE TABLE PLAYER
(
  ID SERIAL NOT NULL,
  NAME VARCHAR (50),
  ABILITY INT NOT NULL DEFAULT 3,
  AGILITY BIGINT NOT NULL,
  SKILL BIGINT NOT NULL,
  INSTINCT BIGINT NOT NULL,
  STAMINA BIGINT NOT NULL,
  LEVEL BIGINT NOT NULL,
  HEALTH BIGINT NOT NULL,
  experience bigint not NULL,
  CONSTRAINT PLAYER_PK PRIMARY KEY (ID)
);


CREATE TABLE EXPERIENCE_TABLE
(
  EXPERINCE INT NOT NULL,
  ABILITY INT NOT NULL DEFAULT 0,
  LEVEL INT NOT NULL DEFAULT 0,
  CONSTRAINT EXPERIENCE_TABLE_PK PRIMARY KEY (EXPERINCE)
)

CREATE TABLE DUEL_REQUEST
(
    ID SERIAL NOT NULL;
    timeOut BIGINT NOT NULL;
    playerOne VARCHAR (50);
    playerTwo VARCHAR (50);
    dataTime DATE;
    CONSTRAINT DUEL_REQUEST_PK PRIMARY KEY (ID)
)
