CREATE TABLE ACCOUNT
(
  ID SERIAL NOT NULL,
  EMAIL VARCHAR (100) NOT NULL,
  PASSWORD VARCHAR (255) NOT NULL,
  CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID)
);

CREATE TABLE HERO
(
  ID SERIAL NOT NULL,
  ACCOUNT_ID BIGINT NOT NULL,
  NAME VARCHAR (50),
  ABILITY INT NOT NULL DEFAULT 3,
  FORCE BIGINT NOT NULL,
  AGILITY BIGINT NOT NULL,
  INSTINCT BIGINT NOT NULL,
  STAMINA BIGINT NOT NULL,
  EXPERIENCE BIGINT NOT NULL,
  LEVEL BIGINT NOT NULL,
  HEALTH BIGINT NOT NULL,
  CONSTRAINT HERO_PK PRIMARY KEY (ID)
);


alter table HERO
    add constraint FK_HERO_ACCOUNT_ID foreign key (ACCOUNT_ID)
      references ACCOUNT (ID)
      on delete restrict on update restrict;

CREATE TABLE EXPERIENCE_TABLE
(
  EXPERIENCE INT NOT NULL,
  ABILITY INT NOT NULL DEFAULT 0,
  LEVEL INT NOT NULL DEFAULT 0,
  CONSTRAINT EXPERIENCE_TABLE_PK PRIMARY KEY (EXPERIENCE)
);

CREATE TABLE DUEL_REQUEST
(
    ID SERIAL NOT NULL,
    TIMEOUT BIGINT NOT NULL,
    HERO_ONE BIGINT NOT NULL,
    HERO_TWO BIGINT,
    DATA_TIME DATE NOT NULL,
    CONSTRAINT DUEL_REQUEST_PK PRIMARY KEY (ID)
);

ALTER TABLE DUEL_REQUEST
   ADD CONSTRAINT FK_DUEL_REQUEST_HERO_ONE FOREIGN KEY (HERO_ONE)
      REFERENCES HERO (ID)
      ON DELETE RESTRICT ON UPDATE RESTRICT;
      
ALTER TABLE DUEL_REQUEST
   ADD CONSTRAINT FK_DUEL_REQUEST_HERO_TWO FOREIGN KEY (HERO_TWO)
      REFERENCES HERO (ID)
      ON DELETE RESTRICT ON UPDATE RESTRICT;
